### ISSUE TITLE
Wrong time zone selection for Moscow

### ISSUE THREAD

**Issue by AsifNowaj** [iansinnott/jstz#4]
Wrong time zone selection for Moscow

Using latest version 1.0.7 jstz.min.js
Browser: Mozilla Firefox version 50.1.0
Step to reproduce
1. Change the computer time zone setting to "(UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2)"
2. Check this library is selecting Asia/Baghdad

But this is working in Chrome 55.0.2883.87

**Comment by iansinnott** [comment]
Hm, my guess is that this is an issue with the underlying library that I originally forked. I didn't write the timezone parsing logic, so I'm not sure what the issue might be. If looks like the original repo has some similar issues though: https://bitbucket.org/pellepim/jstimezonedetect/issues?status=new&status=open

Feel free to reopen if you think that this issue is specific to this fork.
