### ISSUE TITLE
Compare with Moment

### ISSUE THREAD

**Issue by CMCDragonkai** [iansinnott/jstz#6]
Momentjs already has https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/

Is there any difference?

**Comment by iansinnott** [comment]
Good point. Thanks for bringing this up. I actually didn't know moment-tz had that functionality. I started this fork a while back, and the original lib is even older. Maybe moment tz didn't always support `guess()`?

One potential benefit of this library is that it's a standalone dependency, and does not require `moment` in order to work properly. 

Either way, if moment suites your needs then by all means use it. This repo doesn't take much active maintenance so I see no reason not to have both. 

I'd be happy to point people to moment-tz as well in the readme. If you want to PR that I will accept it.
